#!/bin/sh

set -eu

for v in $(pg_buildext supported-versions); do
	pg_virtualenv -v $v -o "shared_preload_libraries=powa,pg_stat_statements" \
		psql -v ON_ERROR_STOP=1 <<-EOF
		CREATE EXTENSION pg_stat_statements;
		CREATE EXTENSION btree_gist;
		CREATE EXTENSION powa;
	EOF
done
